# Generated by Django 4.2.16 on 2024-11-13 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_comment_approved_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('location', 'Location'), ('activities', 'Activities'), ('type_of_post', 'Type of Post')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.tag')),
            ],
            options={
                'verbose_name': 'Post Tag',
                'verbose_name_plural': 'Post Tags',
                'unique_together': {('post', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='adventures.PostTag', to='adventures.tag'),
        ),
    ]
