# Generated by Django 4.2.16 on 2024-11-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_tag_posttag_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttag',
            options={},
        ),
    ]
