# Generated by Django 4.2.16 on 2024-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0007_alter_posttag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AddField(
            model_name='tag',
            name='activity',
            field=models.CharField(blank=True, choices=[('hiking', 'Hiking'), ('camping', 'Camping'), ('fishing', 'Fishing'), ('skiing', 'Skiing'), ('snowboarding', 'Snowboarding'), ('sailing', 'Sailing'), ('kitesurfing', 'Kite Surfing'), ('surfing', 'Surfing'), ('mountainbiking', 'Mountain Biking'), ('foiling', 'foiling'), ('cycling', 'Cycling'), ('running', 'Running')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='location',
            field=models.CharField(blank=True, choices=[('europe', 'Europe'), ('asia', 'Asia'), ('africa', 'Africa'), ('north_america', 'North America'), ('south_america', 'South America'), ('australia', 'Australia'), ('antarctica', 'Antarctica')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='type_choices',
            field=models.CharField(blank=True, choices=[('promo', 'Promo'), ('blog', 'Blog')], max_length=20, null=True),
        ),
    ]
