# Generated by Django 4.2.16 on 2024-11-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_remove_tag_category_tag_activity_tag_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
