# Generated by Django 4.2.16 on 2025-06-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0011_post_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
